name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test-project:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn clean install -DskipTests
    - name: Cache Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
  run-e2e-tests:
    needs: build-test-project
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Pull Dev Code
      run: |
        mkdir dev_code
        cd dev_code
        git clone https://github.com/AnjiB/anji-kot-lin.git
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: |
       cd dev_code/anji-kot-lin
       chmod +x gradlew
    - name: Spinup Environment
      run: |
        cd dev_code/anji-kot-lin
        ./gradlew clean build
        ./gradlew run &
        sleep 30
        curl -v http://localhost:9000/
    - name: test
      run: |
        rm -rf docs
        git add -A
        git commit -m "Cleaning up allure reports"
        git push
        mvn test -Pe2e -DautEnvironment=QA -DenableLogs=true
    - name: Generating Allure Reports
      run: |
        mvn allure:report
    - name: Upload target folder to publish results
      uses: actions/upload-artifact@v2
      with:
        name: target
        path: ./target/
 
  publish-results:
    needs: run-e2e-tests
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Download target folder
      uses: actions/download-artifact@v2
      with:
        name: target
    - name: Publish Allure Reports
      run: |
        mkdir docs
        ls
        mv site/allure-maven-plugin/* docs
        git add -A
        git commit -m "Publishing allure reports"
        git push
